language: python
python:
- '2.7'
services:
- docker
install:
- docker build -t latest .
script:
- docker-compose -f docker-compose.test.yml up
after_success:
- docker login -u $DOCKER_USER -p $DOCKER_PASS
- export REPO=$TRAVIS_REPO_SLUG
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
- echo $REPO:$TAG
- docker build -f Dockerfile -t $REPO:$TAG .
- docker push $REPO
